#!/bin/sh

ENABLED=yes
PROCS=/opt/apps/mors/bin/main/vless-supervisor
ARGS="run"
PREARGS=""
DESC="Mors VLESS supervisor"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/apps/mors/bin/libs/lifecycle_state
case "${1:-}" in
	start|restart) lifecycle_state__runtime_allowed || exit 0 ;;
esac

. /opt/etc/init.d/rc.func
