#!/bin/sh

ENABLED=yes
PROCS=/opt/apps/mors/bin/main/vless-supervisor
ARGS="run"
PREARGS=""
DESC="Mors VLESS supervisor"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
