#!/bin/sh

#------------------------------------------------------------------------------
#
#	ПАКЕТ МОРС
#
#------------------------------------------------------------------------------
#
#	Данный файл служит для начального запуска пакета морс при загрузке системы
#	https://github.com/ndmsystems/packages/wiki/Opkg-Component с командой start
#	основными задачами являются:
#
#	1. Создание таблицы ipset ip4
#	2. Загрузка таблицы ipset доменными именами
#
# ------------------------------------------------------------------------------
#	Разработчик: mail@zeleza.ru
#	Дата создания: 21/05/2022
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

case ${1} in
	start|restart)
		. /opt/apps/mors/bin/libs/vpn
		cmd_mors_init no
		if has_ssr_enable; then
			while /opt/etc/init.d/S22shadowsocks status | grep -q dead
			do
				/opt/etc/init.d/S22shadowsocks restart
				sleep 2
			done
		elif is_vless_over_proxy_enabled; then
			if [ "$(vless_store__is_paused)" = false ] && [ "$(vless_store__enabled_count)" -gt 0 ]; then
				/opt/etc/init.d/S25mors-vless restart >/dev/null 2>&1
			fi
		fi
	;;
esac
