#!/bin/sh


#------------------------------------------------------------------------------
#
#	ПАКЕТ МОРС
#
#------------------------------------------------------------------------------
#
#	Данный файл служит для создания правил для пропуска Shadowsocks трафика (tcp)
#	при использовании любого shadowsocks подключения.
#	Они срабатывают при перезаписи правил в таблице netfilter
#	https://github.com/ndmsystems/packages/wiki/Opkg-Component
#
# ------------------------------------------------------------------------------
#	Разработчик: mail@zeleza.ru
#	Дата создания: 21/05/2022
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

# IPv4
# Роутинг прокси и DNS в nat
# В идеале UDP унести в mangle, но этого пока не сделано
if [ "${type}" = 'iptables' ] && [ "${table}" = 'nat' ] ; then
	. /opt/apps/mors/bin/libs/lifecycle_state
	lifecycle_state__runtime_allowed || exit 0
	. /opt/apps/mors/bin/libs/ndm
	ndm_runtime__begin netfilter_proxy || exit $?

	result=0
	ip4_firewall_set_all_rules &>/dev/null || result=$?
	ndm_runtime__finish "${result}"
	exit $?
fi
