[package]
name = "mors-probe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
mors-domain.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
curl = { version = "0.4", default-features = false }
socket2 = { version = "0.6", features = ["all"] }

[dev-dependencies]
serde_json = "1.0"
